#!/usr/bin/env python3
"""
weightgen_stimulus.py -- single source of truth for the tb_chip_top T4
forced-Z weight-computation test.

Emits, into the run dir:
  weightgen_z.vh       Verilog `force` statements for the tb: the 6 Z_kl pairs
                       (Zpair_i/q[0..5]) + 4 Z_kk diagonals (Zdiag[0..3]) +
                       n_acc, as the 32-bit accumulator words trouper_top wires
                       to reg_bank (reg_bank exposes bits [31:8]).
  weightgen_golden.hex 16 bytes, W shadow 0x30..0x3F, big-endian per
                       reg_write16_be(0x30+4k, w_re) / (0x32+4k, w_im), as
                       produced by trouper's own reference model
                       sim/models/eigvec_fw.compute_eigvec_fw(register_units=True).

The firmware path under test takes NO noise whitening (crt0 zeroes the noise-EMA
state and the tb injects only IRQ_TRAINING_DONE, never IRQ_NOISE_READY), so this
matches compute_eigvec_fw with sigma2_zdiag=None.

Usage:  DESIGN_ROOT=<trouper repo> OUT=<dir> python3 weightgen_stimulus.py
"""
import os
import sys
import pathlib

import numpy as np

_root = os.environ.get("DESIGN_ROOT", "")
if _root and _root not in sys.path:
    sys.path.insert(0, _root)
from sim.models.eigvec_fw import compute_eigvec_fw  # noqa: E402

OUT = pathlib.Path(os.environ.get("OUT", "."))

# --- Stimulus -----------------------------------------------------------------
# A non-degenerate 4-branch channel; Z = scale * h h^H + noise pedestal on the
# diagonal. Values chosen so the register-unit ints are a few thousand -- well
# inside int24, comfortably exercising the int12 normalisation shift.
N_ACC = 4096
h = np.array([1.0 + 0.0j, 0.80 - 0.30j, 0.50 + 0.60j, -0.40 + 0.20j])
scale = 3000.0
noise_pedestal = 800.0

Z_reg = scale * np.outer(h, np.conj(h))
for k in range(4):
    Z_reg[k, k] = Z_reg[k, k].real + noise_pedestal      # real, >0

# Register-unit integers (what reg_read24_be_* returns): off-diagonals signed,
# diagonal unsigned. Round to int, these ARE bits [31:8] of the accumulator.
def rnd(x): return int(np.round(x))

zkl = {}
for (k, l) in [(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]:
    zkl[(k, l)] = (rnd(Z_reg[k, l].real), rnd(Z_reg[k, l].imag))
zdiag = [rnd(Z_reg[k, k].real) for k in range(4)]

# --- Golden: trouper's own reference model -----------------------------------
Zm = np.zeros((4, 4), dtype=complex)
for k in range(4):
    Zm[k, k] = zdiag[k]
for (k, l), (re, im) in zkl.items():
    Zm[k, l] = re + 1j * im
    Zm[l, k] = re - 1j * im

# Returns conj(v) with each component as int16-count/32768.0 (see eigvec_fw.py
# tail: `np.array(w_re, dtype=np.int16) / 32768.0`). Recover the raw int16
# counts the firmware writes with reg_write16_be.
w = compute_eigvec_fw(Zm, n_acc=N_ACC, register_units=True)

def s16(v):
    v = int(round(v)) & 0xFFFF
    return v - 0x10000 if v & 0x8000 else v

wbytes = []
for k in range(4):
    w_re = s16(w[k].real * 32768.0)
    w_im = s16(w[k].imag * 32768.0)
    wbytes += [(w_re >> 8) & 0xFF, w_re & 0xFF, (w_im >> 8) & 0xFF, w_im & 0xFF]
assert len(wbytes) == 16

# --- Emit -------------------------------------------------------------------
def u32(v):  # 32-bit accumulator word: register value in bits [31:8]
    return (int(v) << 8) & 0xFFFFFFFF

pair_ord = [(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]
lines = ["// generated by weightgen_stimulus.py -- do not edit",
         "task force_weightgen_z;", "  begin"]
for idx, kl in enumerate(pair_ord):
    re, im = zkl[kl]
    lines.append(f"    force dut.u_trouper.Zpair_i[{idx}] = 32'h{u32(re):08x};  // Z{kl[0]}{kl[1]}_I reg {re}")
    lines.append(f"    force dut.u_trouper.Zpair_q[{idx}] = 32'h{u32(im):08x};  // Z{kl[0]}{kl[1]}_Q reg {im}")
for k in range(4):
    lines.append(f"    force dut.u_trouper.Zdiag[{k}]    = 32'h{u32(zdiag[k]):08x};  // ZDIAG{k} reg {zdiag[k]}")
lines.append(f"    force dut.u_trouper.n_acc        = 18'd{N_ACC};")
lines += ["  end", "endtask", ""]
(OUT / "weightgen_z.vh").write_text("\n".join(lines))

(OUT / "weightgen_golden.hex").write_text("".join("%02x\n" % b for b in wbytes))

print("weightgen_stimulus: n_acc=%d" % N_ACC)
print("  Z_kl (reg units):", zkl)
print("  ZDIAG (reg units):", zdiag)
print("  golden W[0x30..0x3F]:", " ".join("%02x" % b for b in wbytes))
