// arty_top.v
// Vivado-only top for the Arty A7-100T: generates the 32 MHz HCLK domain fpga_top.v (and
// Trouper's single-clock RTL) expects from the board's 100 MHz oscillator via the Clocking
// Wizard IP (clk_wiz_0, created in vivado/create_project.tcl -- same CONFIG.RESET_TYPE
// ACTIVE_LOW/CONFIG.RESET_PORT resetn convention as lora-mimo/fpga-emul/vivado/create_project.tcl's
// clk_wiz_0), synchronizes the board reset into that domain gated on MMCM lock, and maps
// fpga_top's status/debug signals onto board LEDs and a Pmod header.
//
// led[2:0] = fpga_top's {FAIL, PASS, DONE} status latch (see ahb_gpio_dbg.v).
// led[3]   = MMCM locked (clock-alive heartbeat -- lit solid once the 32 MHz domain is up,
//            independent of whether the firmware test has run yet).

`default_nettype none

module arty_top (
    input  wire       CLK100MHZ,
    input  wire       ck_rst,        // Arty board reset button, active-low

    output wire [3:0] led,

    // Pmod header debug passthrough -- optional scope probe points, also natural ILA taps.
    output wire       pmod_host_cs,
    output wire       pmod_spi_sck,
    output wire       pmod_spi_mosi,
    output wire       pmod_spi_miso
);

    wire hclk_32m;
    wire mmcm_locked;

    // Clocking Wizard IP, generated by vivado/create_project.tcl: 100 MHz -> 32 MHz,
    // active-low reset input matching ck_rst's polarity directly.
    clk_wiz_0 u_clk_wiz (
        .clk_in1  (CLK100MHZ),
        .clk_out1 (hclk_32m),
        .resetn   (ck_rst),
        .locked   (mmcm_locked)
    );

    // 2-FF synchronizer releasing HRESETn into the 32 MHz domain only once the MMCM is locked;
    // held in reset immediately (asynchronously) on the board reset button or MMCM unlock.
    reg [1:0] rst_sync;
    always @(posedge hclk_32m or negedge ck_rst) begin
        if (!ck_rst) rst_sync <= 2'b00;
        else         rst_sync <= {rst_sync[0], mmcm_locked};
    end
    wire HRESETn = rst_sync[1];

    wire [2:0] status_led;

    fpga_top u_fpga_top (
        .HCLK         (hclk_32m),
        .HRESETn      (HRESETn),
        .led          (status_led),
        .dbg_host_cs  (pmod_host_cs),
        .dbg_spi_sck  (pmod_spi_sck),
        .dbg_spi_mosi (pmod_spi_mosi),
        .dbg_spi_miso (pmod_spi_miso)
    );

    assign led[2:0] = status_led;
    assign led[3]   = mmcm_locked;

endmodule

`default_nettype wire
