// tb_chip_top.v
// End-to-end connectivity + firmware test for chip_top (Open Item #1). A real
// Grouper CPU drives MMIO traffic across the full cross-project path
//
//   picorv32 -> cpu_ss -> ahb_conn_buff CPU->periph pipe -> periph_ss
//   -> interconnect_ss (EXT_PERIPH decode) -> ext_ahb_m_if
//   -> ahb_to_grp_bridge  (HCLK 25 MHz  ->  IQ_CLK 32 MHz  bundled-data CDC)
//   -> trouper_top GRP_* bus -> register arbiter -> reg_bank
//
// with real RTL on both sides. Results are read back over Trouper's SPI slave.
//
// Two modes, selected by +FW=<mode>:
//
//   +FW=smoke   (default) -- a hand-assembled program in ROM
//     T1  MIMO_CTRL single GRP write
//     T2  W shadow 0x33..0x3F written per byte lane
//     T3a aligned + non-word-aligned GRP reads (the periph_ss lane-replicate
//         fix -- see integration/planning/grp-ext-periph-byte-lane.md)
//     T3b CPU reconstructs Z_01_I (0x40..0x42) into W 0x30..0x32
//
//   +FW=weightgen -- Trouper's real firmware/picorv32 MRC weight-computation
//     image (crt0.S + main.c), built for Grouper's map (ASIC_REG_BASE=
//     0x80010000) and loaded into RAM. The testbench force-loads a known Z_kl /
//     Z_kk vector (weightgen_z.vh, generated by fw/weightgen_stimulus.py) and
//     injects IRQ_TRAINING_DONE; the firmware runs the 8-iteration fixed-point
//     power method and writes conj(v) as Q1.15 to the W shadow bank. T4 checks
//     0x30..0x3F over SPI against weightgen_golden.hex -- the same bytes
//     produced by trouper's own sim/models/eigvec_fw.compute_eigvec_fw().
//
// Firmware load, selected by +LOAD=<how> (weightgen only):
//   +LOAD=uart      (default) model Grouper's ROM bootloader host: send the
//                   image over UART_RX with the W/B wire protocol, let the ROM
//                   bootloader write RAM and bank-switch. Exercises the real
//                   boot path.
//   +LOAD=backdoor  $readmemh the per-lane image straight into ram_ss's four
//                   sram1024x8 models and force bank_switch=1. Fast; skips boot.
//
// Built with -DIQ (runner: STIM=iq) this becomes T5: a real sigma-delta IQ
// capture (fw/iq_stimulus.py, reusing Trouper's cocotb iq_capture front-end) is
// clocked onto the radio pads, a psram_model is wired onto chip_top's PSRAM
// nets, the tb SPI-provisions Trouper (SF/BW/SC_THR/RX_HOLD/PSRAM) with the CPU
// held in reset, then releases the CPU so the real weight-gen firmware reads a
// *measured* Z over the bridge and writes weights. The measured Z + N_ACC + the
// firmware's W are dumped to iq_result.txt; fw/check_weightgen_iq.py does the
// bit-exact compare against eigvec_fw.compute_eigvec_fw(measured Z). Implies
// FW=weightgen, LOAD=backdoor. See planning/tb-chip-top.md.
//
// Simulator: Verilator 5, --binary --timing. Run: scripts/run_tb_chip_top.sh.

`timescale 1ns/1ps
`default_nettype none

module tb_chip_top;

    // ---- Clocks -----------------------------------------------------------
    reg hclk   = 1'b0;
    reg iq_clk = 1'b0;
    always #20.000  hclk   = ~hclk;    // 25 MHz  (Grouper HCLK, test chip)
    always #15.625  iq_clk = ~iq_clk;  // 32 MHz  (Trouper IQ_CLK)

    reg hresetn = 1'b0;

    // ---- Trouper radio pads ------------------------------------------------
`ifdef IQ
    // STIM=iq: driven from the sigma-delta capture playback (see the IQ block).
    reg iq_i0 = 1'b0, iq_i1 = 1'b0, iq_i2 = 1'b0, iq_i3 = 1'b0;
    reg iq_q0 = 1'b0, iq_q1 = 1'b0, iq_q2 = 1'b0, iq_q3 = 1'b0;
`else
    wire iq_i0 = 1'b0, iq_i1 = 1'b0, iq_i2 = 1'b0, iq_i3 = 1'b0;
    wire iq_q0 = 1'b0, iq_q1 = 1'b0, iq_q2 = 1'b0, iq_q3 = 1'b0;
`endif

    // ---- Grouper pads --------------------------------------------------
    wire        uart_tx;
    reg         uart_rx = 1'b1;         // idle high; driven by the bootload BFM
    wire [15:0] gpio;

    // ---- Trouper misc outputs ---------------------------------------
    wire remod_i, remod_q;
    wire psram_sck, psram_ce_n;
    wire psram_sio0, psram_sio1, psram_sio2, psram_sio3;
    wire irq_out;

    // ---- SPI oracle pads (host side) ------------------------------------
    reg  spi_cs   = 1'b1;
    reg  spi_sck  = 1'b0;
    reg  spi_mosi = 1'b0;
    wire spi_miso;

    // =====================================================================
    // DUT
    // =====================================================================
    chip_top dut (
        .HCLK        (hclk),
        .IQ_CLK      (iq_clk),
        .HRESETn     (hresetn),

        .IQ_DATA_I_0 (iq_i0), .IQ_DATA_I_1 (iq_i1),
        .IQ_DATA_I_2 (iq_i2), .IQ_DATA_I_3 (iq_i3),
        .IQ_DATA_Q_0 (iq_q0), .IQ_DATA_Q_1 (iq_q1),
        .IQ_DATA_Q_2 (iq_q2), .IQ_DATA_Q_3 (iq_q3),
        .REMOD_A_I   (remod_i), .REMOD_A_Q (remod_q),

        .PSRAM_SCK   (psram_sck), .PSRAM_CE_N (psram_ce_n),
        .PSRAM_SIO_0 (psram_sio0), .PSRAM_SIO_1 (psram_sio1),
        .PSRAM_SIO_2 (psram_sio2), .PSRAM_SIO_3 (psram_sio3),

        .HOST_CS     (spi_cs),
        .SPI_SCK     (spi_sck),
        .SPI_MOSI    (spi_mosi),
        .SPI_MISO    (spi_miso),

        .IRQ_OUT     (irq_out),

        .UART_TX     (uart_tx),
        .UART_RX     (uart_rx),
        .GPIO_0 (gpio[0]),  .GPIO_1 (gpio[1]),  .GPIO_2 (gpio[2]),  .GPIO_3 (gpio[3]),
        .GPIO_4 (gpio[4]),  .GPIO_5 (gpio[5]),  .GPIO_6 (gpio[6]),  .GPIO_7 (gpio[7]),
        .GPIO_8 (gpio[8]),  .GPIO_9 (gpio[9]),  .GPIO_10(gpio[10]), .GPIO_11(gpio[11]),
        .GPIO_12(gpio[12]), .GPIO_13(gpio[13]), .GPIO_14(gpio[14]), .GPIO_15(gpio[15])
    );

    // Hierarchy shorthands -------------------------------------------------
    `define ROM  dut.u_grouper.u_grouper_soc_dig_ss.u_rom_ss.memory
    `define RAM0 dut.u_grouper.u_grouper_soc_dig_ss.u_ram_ss.gen_macro_ram.gen_sram[0].u_wrapper.u_sram_macro.mem
    `define RAM1 dut.u_grouper.u_grouper_soc_dig_ss.u_ram_ss.gen_macro_ram.gen_sram[1].u_wrapper.u_sram_macro.mem
    `define RAM2 dut.u_grouper.u_grouper_soc_dig_ss.u_ram_ss.gen_macro_ram.gen_sram[2].u_wrapper.u_sram_macro.mem
    `define RAM3 dut.u_grouper.u_grouper_soc_dig_ss.u_ram_ss.gen_macro_ram.gen_sram[3].u_wrapper.u_sram_macro.mem
    `define BANKSW dut.u_grouper.u_grouper_soc_dig_ss.u_cpu_ss.bank_switch
    `define CPU_RSTN dut.u_grouper.u_grouper_soc_dig_ss.u_cpu_ss.cpu_rst_n

    // =====================================================================
    // STIM=iq: real sigma-delta capture playback + PSRAM model (T5)
    // =====================================================================
`ifdef IQ
    `include "iq_stim.cfg.vh"     // `define IQ_SF / IQ_BWSEL / IQ_NSAMP  (generated)
    localparam        IQ_MAX  = 1 << 22;      // must match fw/iq_stimulus.py
    localparam [7:0]  IQ_SF   = `IQ_SF;
    localparam [7:0]  IQ_BWSEL= `IQ_BWSEL;
    localparam integer IQ_NSAMP = `IQ_NSAMP;

    reg  [7:0] iq_stim [0:IQ_MAX-1];          // one packed nibble-pair per IQ_CLK
    integer    iq_ptr = 0;
    reg        iq_run = 1'b0;

    always @(posedge iq_clk) if (iq_run) begin
        {iq_q3, iq_q2, iq_q1, iq_q0} <= iq_stim[iq_ptr][7:4];
        {iq_i3, iq_i2, iq_i1, iq_i0} <= iq_stim[iq_ptr][3:0];
        if (iq_ptr < IQ_NSAMP - 1) iq_ptr <= iq_ptr + 1;
    end

    // chip_top is a P&R-only model: PSRAM_SIO_* are plain outputs with no pad
    // OE, and it self-loops psram_sio_in <= PSRAM_SIO (== psram_sio_out). The
    // real DSP path needs a working PSRAM (delay line + INIT_DONE), so attach
    // Trouper's own behavioural model onto the internal nets and override the
    // self-loop: a read (controller tri-stated, oe=0) sees the model.
    wire [3:0] ps_oe  = {dut.psram_sio_oe_3,  dut.psram_sio_oe_2,
                         dut.psram_sio_oe_1,  dut.psram_sio_oe_0};
    wire [3:0] ps_out = {dut.psram_sio_out_3, dut.psram_sio_out_2,
                         dut.psram_sio_out_1, dut.psram_sio_out_0};
    wire [3:0] ps_model_in;

    psram_model #(.ADDR_BITS(16), .RD_LAUNCH_SKIP(3)) u_psram (
        .clk_32m (iq_clk),
        .rst_n   (hresetn),
        .ce_n    (psram_ce_n),
        .sio_out (ps_out),
        .sio_oe  (ps_oe),
        .sio_in  (ps_model_in)
    );

    initial begin
        force dut.psram_sio_in_0 = ps_oe[0] ? ps_out[0] : ps_model_in[0];
        force dut.psram_sio_in_1 = ps_oe[1] ? ps_out[1] : ps_model_in[1];
        force dut.psram_sio_in_2 = ps_oe[2] ? ps_out[2] : ps_model_in[2];
        force dut.psram_sio_in_3 = ps_oe[3] ? ps_out[3] : ps_model_in[3];
    end
`endif

    // =====================================================================
    // Forced Z (smoke: a recognisable pattern; weightgen: from the stimulus)
    // =====================================================================
    task force_z_smoke;
        begin
            force dut.u_trouper.Zpair_i[0] = 32'h11223300;
            force dut.u_trouper.Zpair_q[0] = 32'h44556600;
            force dut.u_trouper.Zpair_i[1] = 32'h77889900;
            force dut.u_trouper.Zpair_q[1] = 32'hAABBCC00;
            force dut.u_trouper.Zpair_i[2] = 32'hDDEEF000;
            force dut.u_trouper.Zpair_q[2] = 32'h12345600;
        end
    endtask
`include "weightgen_z.vh"   // defines task force_weightgen_z (generated)

    // =====================================================================
    // SPI master model (Mode 0, MSB first)
    // =====================================================================
    localparam real SCK_HALF = 62.5;   // 8 MHz

    task spi_byte(input [7:0] tx, output [7:0] rx);
        integer b;
        begin
            for (b = 7; b >= 0; b = b - 1) begin
                spi_mosi = tx[b];
                #(SCK_HALF);
                spi_sck = 1'b1;
                rx = {rx[6:0], spi_miso};
                #(SCK_HALF);
                spi_sck = 1'b0;
            end
        end
    endtask

    task spi_start; begin spi_cs = 1'b0; #(SCK_HALF); end endtask
    task spi_stop;  begin #(SCK_HALF); spi_cs = 1'b1; #500; end endtask

    task spi_read(input [6:0] a, output [7:0] d);
        reg [7:0] dump;
        begin
            spi_start;
            spi_byte({1'b1, a}, dump);
            spi_byte(8'h00, d);
            spi_stop;
        end
    endtask

    task spi_write(input [6:0] a, input [7:0] d);
        reg [7:0] dump;
        begin
            spi_start;
            spi_byte({1'b0, a}, dump);
            spi_byte(d, dump);
            spi_stop;
        end
    endtask

    reg [7:0] burst [0:15];
    task spi_read_burst(input [6:0] a, input integer n);
        integer k; reg [7:0] dump;
        begin
            spi_start;
            spi_byte({1'b1, a}, dump);
            for (k = 0; k < n; k = k + 1) spi_byte(8'h00, burst[k]);
            spi_stop;
        end
    endtask

    // =====================================================================
    // Firmware load
    // =====================================================================
    integer NWORDS;                       // set from weightgen.nwords.txt

    // --- backdoor: image straight into RAM, skip the bootloader ----------
    reg [7:0] lane0 [0:1023], lane1 [0:1023], lane2 [0:1023], lane3 [0:1023];
    task load_backdoor;
        integer i;
        begin
            for (i = 0; i < 1024; i = i + 1)
                {lane0[i], lane1[i], lane2[i], lane3[i]} = 32'h0;
            $readmemh("weightgen.lane0.hex", lane0);
            $readmemh("weightgen.lane1.hex", lane1);
            $readmemh("weightgen.lane2.hex", lane2);
            $readmemh("weightgen.lane3.hex", lane3);
            for (i = 0; i < 1024; i = i + 1) begin
                `RAM0[i] = lane0[i];
                `RAM1[i] = lane1[i];
                `RAM2[i] = lane2[i];
                `RAM3[i] = lane3[i];
            end
            force `BANKSW = 1'b1;          // RAM answers at 0; CPU boots from RAM
            $display("load: backdoor (%0d words into RAM, bank_switch forced)", NWORDS);
        end
    endtask

    // --- uart: model the ROM bootloader host over UART_RX ---------------
    // Grouper UART is 8N1 (uart_tx.sv: START/data/STOP, no parity). build_
    // bootloader.sh is invoked --baud 625000, which is clk_div=0 at 25 MHz
    // (bit period = (clk_div+1)*8 / SYS_CLK_HZ = 8/25e6 = 320 ns).
    localparam real UART_BIT_NS = 320.0;

    reg [7:0] imgbyte [0:4095];            // raw firmware.bin

    task uart_tx_byte(input [7:0] b);
        integer k;
        begin
            uart_rx = 1'b0; #(UART_BIT_NS);          // start
            for (k = 0; k < 8; k = k + 1) begin
                uart_rx = b[k]; #(UART_BIT_NS);      // LSB first
            end
            uart_rx = 1'b1; #(UART_BIT_NS);          // stop
        end
    endtask

    task uart_wait_for_lf;                 // bootloader prints "hi\n" on ready
        integer bit_i, guard;
        reg [7:0] rxb;
        begin
            guard = 0;
            rxb = 8'h00;
            while (rxb !== 8'h0A && guard < 200000) begin
                @(negedge uart_tx);                 // start bit
                #(UART_BIT_NS * 1.5);
                for (bit_i = 0; bit_i < 8; bit_i = bit_i + 1) begin
                    rxb[bit_i] = uart_tx; #(UART_BIT_NS);
                end
                guard = guard + 1;
            end
        end
    endtask

    task uart_tx_u32(input [31:0] w);      // big-endian
        begin
            uart_tx_byte(w[31:24]); uart_tx_byte(w[23:16]);
            uart_tx_byte(w[15:8]);  uart_tx_byte(w[7:0]);
        end
    endtask

    task load_uart;
        integer i, w;
        begin
            for (i = 0; i < 4096; i = i + 1) imgbyte[i] = 8'h00;
            $readmemh("weightgen.bytes.hex", imgbyte);   // one byte/line
            uart_wait_for_lf;
            uart_tx_byte("W");
            uart_tx_u32(32'h4000_0000);                  // RAM alias base
            uart_tx_u32(NWORDS);
            for (w = 0; w < NWORDS; w = w + 1)
                uart_tx_u32({imgbyte[4*w+3], imgbyte[4*w+2],
                             imgbyte[4*w+1], imgbyte[4*w+0]});   // word LE in file -> BE on wire
            uart_tx_byte("B");
            $display("load: uart bootloader (%0d words sent, then 'B')", NWORDS);
        end
    endtask

    // =====================================================================
    // Scoreboard
    // =====================================================================
    integer errors = 0;
    task check(input [511:0] name, input [7:0] got, input [7:0] exp);
        begin
            if (got !== exp) begin
                $display("FAIL  %-46s got 0x%02h expected 0x%02h", name, got, exp);
                errors = errors + 1;
            end else
                $display("pass  %-46s 0x%02h", name, got);
        end
    endtask

    // =====================================================================
    // Test sequence
    // =====================================================================
    reg [7:0] rd;
    reg [7:0] golden [0:15];
    integer   i;
    reg [1023:0] fw_mode, load_mode;

    localparam [6:0] ADDR_CHIP_ID = 7'h00;
    localparam [6:0] ADDR_MIMO    = 7'h08;
    localparam [6:0] ADDR_SCTHR_H = 7'h0C;
    localparam [6:0] ADDR_SCTHR_L = 7'h0D;
    localparam [6:0] ADDR_W_BASE  = 7'h30;
    localparam [6:0] ADDR_Z_BASE  = 7'h40;

    initial begin
`ifdef DUMP
        $dumpfile("tb_chip_top.vcd");
        $dumpvars(0, tb_chip_top);
`endif
        if (!$value$plusargs("FW=%s",   fw_mode))   fw_mode   = "smoke";
        if (!$value$plusargs("LOAD=%s", load_mode)) load_mode = "uart";
        NWORDS = 0;
        begin : rd_nwords
            integer fd, n;
            fd = $fopen("weightgen.nwords.txt", "r");
            if (fd) begin n = $fscanf(fd, "%d", NWORDS); $fclose(fd); end
        end

        if (fw_mode == "weightgen") begin
`ifdef IQ
            // T5: Z is measured from real samples, not forced. Hold the Grouper
            // CPU in reset from the outset so it cannot run asic_cfg_commit()
            // (which releases RX_HOLD over GRP) before run_weightgen_iq has
            // SPI-provisioned SF/BW -- those writes are RX_HOLD-gated.
            force `CPU_RSTN = 1'b0;
            $readmemh("iq_stim.hex", iq_stim);
`else
            force_weightgen_z;
            $readmemh("weightgen_golden.hex", golden);
`endif
            if (load_mode == "backdoor") load_backdoor;
            // ROM keeps whatever code.hex holds (the bootloader for uart mode;
            // unused for backdoor). Load it so a bad CWD fails loudly.
            $readmemh("code.hex", `ROM);
        end else begin
            force_z_smoke;
            $readmemh("code.hex", `ROM);
            if (`ROM[0] === 32'hx || `ROM[0] === 32'h0) begin
                $display("FATAL  ROM word 0 = %08x -- code.hex not loaded", `ROM[0]);
                $finish;
            end
        end

        hresetn = 1'b0;
        repeat (20) @(posedge hclk);
        hresetn = 1'b1;

`ifdef IQ
        run_weightgen_iq;
`else
        if (fw_mode == "weightgen") run_weightgen;
        else                        run_smoke;
`endif

        if (errors == 0) $display("\nTB PASS (%0s / %0s)", fw_mode, load_mode);
        else             $display("\nTB FAIL - %0d error(s) (%0s / %0s)", errors, fw_mode, load_mode);
        $finish;
    end

    // ---- smoke (T1..T3) ------------------------------------------------
    task run_smoke;
        begin : sm
            integer bad;
            reg [7:0] exp;
            repeat (8000) @(posedge hclk);

            spi_read(ADDR_CHIP_ID, rd);
            check("CHIP_ID over SPI (oracle sanity)", rd, 8'hA7);
            spi_read(ADDR_MIMO, rd);                 // priming, discard

            spi_read(ADDR_MIMO, rd);
            check("T1  MIMO_CTRL  <- CPU GRP write", rd, 8'h31);

            spi_read_burst(ADDR_W_BASE, 16);
            bad = 0;
            for (i = 0; i < 16; i = i + 1) begin
                exp = (i < 3) ? (8'h11 + 8'h11 * i[7:0]) : (8'hB0 + i[7:0]);
                if (burst[i] !== exp) begin
                    $display("FAIL  W[0x%02h]  got 0x%02h expected 0x%02h", 8'h30+i, burst[i], exp);
                    bad = bad + 1;
                end
            end
            if (bad == 0) begin
                $display("pass  T3b W[0x30..0x32] = Z_01_I bytes copied by CPU  (0x11 0x22 0x33)");
                $display("pass  T2  W[0x33..0x3F] <- CPU GRP write, all byte lanes  (0xB3..0xBF)");
            end
            errors = errors + bad;

            spi_read(ADDR_Z_BASE + 7'h00, rd); check("T3  Z[0x40] forced (SPI ground truth)", rd, 8'h11);
            spi_read(ADDR_Z_BASE + 7'h01, rd); check("T3  Z[0x41] forced (SPI ground truth)", rd, 8'h22);
            spi_read(ADDR_Z_BASE + 7'h02, rd); check("T3  Z[0x42] forced (SPI ground truth)", rd, 8'h33);
            spi_read(ADDR_SCTHR_H, rd); check("T3a CPU aligned   GRP read  (lbu 0x08 -> 0x0C)", rd, 8'h31);
            spi_read(ADDR_SCTHR_L, rd); check("T3a CPU unaligned GRP read  (lbu 0x09 -> 0x0D)", rd, 8'h07);
        end
    endtask

    // ---- weightgen (T4) --------------------------------------------
    task run_weightgen;
        begin : wg
            integer bad;
            if (load_mode == "uart") load_uart;

            // Let crt0 + asic_cfg_commit() run, then hand the firmware a
            // one-shot training_done. A *pulse* (not a hold): the edge sets
            // rb_irq_set[1] -> irq_status latches TRAINING_DONE until the
            // firmware's IRQ_CLEAR, while packet_ctrl_fsm sees only a blip and
            // never drives a bogus packet_active / W_valid (holding it high
            // spuriously gates the W-shadow writes -- see git history).
            repeat (2000) @(posedge hclk);
            force dut.u_trouper.training_done = 1'b1;
            repeat (3) @(posedge iq_clk);
            release dut.u_trouper.training_done;

            // 8-iteration fixed-point power method + ~30 GRP reads + config +
            // 8 W writes + W_COMMIT. ~36.5k CPU cycles per the fw benchmark;
            // 400k HCLK is a wide margin over that plus bridge latency.
            repeat (400000) @(posedge hclk);

            // Quiesce the CPU before the SPI oracle read: main() loops forever
            // polling IRQ_STATUS over the GRP bus, and a live GRP access
            // hijacks reg_bank's shared combinational read port
            // (rb_raddr = grp_active ? GRP_ADDR : spi_rd_addr), corrupting
            // whichever SPI burst bytes coincide with a poll. Holding the
            // picorv32 in reset stops GRP traffic; reg_bank keeps its state
            // (IQ_CLK domain, untouched by the Grouper reset).
            force dut.u_grouper.u_grouper_soc_dig_ss.u_cpu_ss.cpu_rst_n = 1'b0;
            repeat (200) @(posedge iq_clk);

            spi_read_burst(ADDR_W_BASE, 16);
            bad = 0;
            for (i = 0; i < 16; i = i + 1)
                if (burst[i] !== golden[i]) begin
                    $display("FAIL  W[0x%02h]  got 0x%02h expected 0x%02h (eigvec_fw)",
                             8'h30 + i, burst[i], golden[i]);
                    bad = bad + 1;
                end
            if (bad == 0)
                $display("pass  T4  W shadow 0x30..0x3F == eigvec_fw golden (real weightgen fw on real CPU)");
            errors = errors + bad;
        end
    endtask

    // ---- weightgen + real IQ (T5) ---------------------------------------
    // Drive a real sigma-delta capture through Trouper's DSP chain so training
    // produces Z for real, then let the real weight-gen firmware read that Z
    // over the AHB->GRP bridge and write MRC weights. The bit-exact oracle is
    // fw/check_weightgen_iq.py (runs post-sim on the dumped Z + W).
`ifdef IQ
    task run_weightgen_iq;
        begin : wgiq
            integer bad, guard, k;
            reg [7:0] zb  [0:47];             // Z region 0x40..0x6F
            reg [7:0] wb  [0:15];             // W shadow 0x30..0x3F
            reg [7:0] nacc_hi, nacc_mid, nacc_lo;
            integer fd;

            // CPU is already held in reset (forced in the initial block). If
            // uart-loading, the bootloader needs it running -- not supported
            // for IQ; the runner pins LOAD=backdoor.
            if (load_mode == "uart")
                $display("WARN  LOAD=uart not supported with STIM=iq; using backdoor RAM image");

            repeat (50) @(posedge iq_clk);

            // ---- host config over SPI (CPU held: no GRP/SPI read-port race).
            // Mirrors trouper test_capture_playback: SF, BW, SC_THR=0x0100,
            // SC_HITS_REQ=0, release RX_HOLD, enable PSRAM.
            spi_read(7'h00, rd);                       // settle
            spi_read(7'h09, rd);
            spi_write(7'h09, IQ_SF);                   // SF_CFG
            spi_write(7'h0A, {7'h0, IQ_BWSEL[0]});    // BW_CFG[0] bw_sel
            spi_read(7'h0A, rd);
            if ((rd & 8'h01) !== IQ_BWSEL[0])
                $display("WARN  BW_CFG readback 0x%02h (wanted bit0=%b)", rd, IQ_BWSEL[0]);
            spi_write(7'h0C, 8'h01);                   // SC_THR[15:8]
            spi_write(7'h0D, 8'h00);                   // SC_THR[7:0]  -> 0x0100
            spi_write(7'h0E, 8'h00);                   // SC_HITS_REQ = 0
            spi_write(7'h1A, 8'h00);                   // release RX_HOLD
            spi_write(7'h70, 8'h01);                   // PSRAM enable

            // ---- poll PSRAM INIT_DONE (0x71[3]) -----------------------------
            guard = 0; rd = 8'h00;
            while (!(rd & 8'h08) && guard < 4000) begin
                repeat (200) @(posedge iq_clk);
                spi_read(7'h71, rd);
                guard = guard + 1;
            end
            if (!(rd & 8'h08)) begin
                $display("FAIL  PSRAM INIT_DONE never set (0x71=0x%02h)", rd);
                errors = errors + 1;
                disable wgiq;
            end
            $display("iq: PSRAM init OK (%0d polls)", guard);

            // ---- start playback, release the CPU into the weight-gen fw -----
            iq_ptr = 0;
            iq_run = 1'b1;
            release `CPU_RSTN;
            $display("iq: playback started (%0d samples), weight-gen fw running", IQ_NSAMP);

            // ---- wait for a REAL training_done from the DSP chain ----------
            guard = 0;
            while (dut.u_trouper.training_done !== 1'b1 && guard < 6_000_000) begin
                @(posedge iq_clk);
                guard = guard + 1;
            end
            if (dut.u_trouper.training_done !== 1'b1) begin
                $display("FAIL  no training_done after %0d iq_clk (sc_lock=%b) -- widen IQ_NSAMP / move IQ_START",
                         guard, dut.u_trouper.sc_lock);
                errors = errors + 1;
                disable wgiq;
            end
            $display("iq: training_done at iq_clk +%0d  (sc_lock=%b)",
                     guard, dut.u_trouper.sc_lock);

            // ---- firmware compute budget (same as T4) ---------------------
            repeat (400000) @(posedge hclk);

            // ---- quiesce CPU, SPI-oracle dump measured Z + n_acc + fw W ----
            force `CPU_RSTN = 1'b0;
            repeat (200) @(posedge iq_clk);

            spi_read_burst(7'h30, 16);
            for (k = 0; k < 16; k = k + 1) wb[k] = burst[k];
            spi_read_burst(7'h40, 16);
            for (k = 0; k < 16; k = k + 1) zb[k] = burst[k];
            spi_read_burst(7'h50, 16);
            for (k = 0; k < 16; k = k + 1) zb[16 + k] = burst[k];
            spi_read_burst(7'h60, 16);
            for (k = 0; k < 16; k = k + 1) zb[32 + k] = burst[k];
            spi_read(7'h21, nacc_hi);
            spi_read(7'h22, nacc_mid);
            spi_read(7'h23, nacc_lo);

            fd = $fopen("iq_result.txt", "w");
            $fwrite(fd, "NACC %02x %02x %02x\n", nacc_hi, nacc_mid, nacc_lo);
            $fwrite(fd, "Z");
            for (k = 0; k < 48; k = k + 1) $fwrite(fd, " %02x", zb[k]);
            $fwrite(fd, "\nW");
            for (k = 0; k < 16; k = k + 1) $fwrite(fd, " %02x", wb[k]);
            $fwrite(fd, "\n");
            $fclose(fd);
            $display("iq: wrote iq_result.txt  n_acc=0x%02h%02h%02h",
                     nacc_hi & 8'h03, nacc_mid, nacc_lo);

            // ---- tb-side sanity; bit-exact match is check_weightgen_iq.py --
            bad = 0;
            for (k = 0; k < 16; k = k + 1) if (wb[k] !== 8'h00) bad = bad + 1;
            if (bad == 0) begin
                $display("FAIL  T5 W shadow all-zero -- firmware wrote no weights");
                errors = errors + 1;
            end else
                $display("pass  T5 firmware wrote W shadow (%0d/16 bytes nonzero); check_weightgen_iq.py does the bit-exact compare", bad);
        end
    endtask
`endif

    initial begin
`ifdef IQ
        #900_000_000;                      // capture playback + compute
`else
        #120_000_000;                      // weightgen compute + UART load
`endif
        $display("TB FAIL - timeout (no $finish reached)");
        $finish;
    end

    // Probe: every GRP write that reaches reg_bank in the W-shadow window.
`ifdef PROBE
    always @(posedge iq_clk)
        if (dut.u_trouper.ce_16m && dut.u_trouper.rb_we &&
            dut.u_trouper.rb_addr[7:4] == 4'h3)
            $display("[%0t] GRP W  w_shadow[0x%02h] <= 0x%02h  W_valid=%b pkt_active=%b wr_rej=%b",
                     $time, dut.u_trouper.rb_addr, dut.u_trouper.rb_wdata,
                     dut.u_trouper.W_valid, dut.u_trouper.packet_active,
                     dut.u_trouper.u_rb.w_wr_rejected);
    always @(posedge dut.u_trouper.W_valid)
        $display("[%0t] W_valid RISE  (packet_active=%b)", $time, dut.u_trouper.packet_active);
    always @(dut.u_trouper.u_rb.w_shadow_r[9])
        $display("[%0t] w_shadow_r[9]  = 0x%02h", $time, dut.u_trouper.u_rb.w_shadow_r[9]);
    always @(dut.u_trouper.u_rb.w_shadow_r[10])
        $display("[%0t] w_shadow_r[10] = 0x%02h", $time, dut.u_trouper.u_rb.w_shadow_r[10]);
`endif

endmodule

`default_nettype wire
